# Generated by Django 4.0.4 on 2022-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_name', models.CharField(max_length=30)),
                ('pin_description', models.CharField(max_length=100)),
                ('pin_image', models.ImageField(upload_to='pins/')),
            ],
        ),
    ]
