# Generated by Django 4.0.4 on 2022-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_image',
            field=models.ImageField(unique=True, upload_to='pins/'),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
