# Generated by Django 4.0.4 on 2022-05-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_location_alter_pin_pin_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['pin_name']},
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin_category',
            new_name='category',
        ),
    ]
