# Generated by Django 4.0.4 on 2022-05-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
