# Generated by Django 4.0.4 on 2022-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pin_options_rename_pin_category_pin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
