# Generated by Django 4.0.4 on 2022-05-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
