# Generated by Django 4.0.4 on 2022-05-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
            preserve_default=False,
        ),
    ]
