# Generated by Django 4.0.4 on 2022-05-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_pin_remove_image_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={},
        ),
    ]
