# Generated by Django 4.0.4 on 2022-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_description',
            field=models.TextField(),
        ),
    ]
