# Generated by Django 4.0.4 on 2022-05-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pin_pin_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='location',
            new_name='Location',
        ),
    ]
